# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a7be3e0def93d2abef397ee9988921742fba8543c6c2446580b2156215052520d53f1deb42012ae447a20b0fea5123b91df551795144e6a91dc2d2603ef87d0c

test:
  secret_key_base: 1e7de86f9c912152adcdabc8880264a2dc9ced93292213b677e36e8faefbfb0c14c881a948b47cc7de622e2dfdd0835997cba7b96523edb5c400a4a40fb17c0f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
